[package]
name = "vtysh-helper"
version = "0.6.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4", features = ["derive"] }
prost = "0.11"
tokio = { version="1", features = ["full"] }
tokio-stream = "0.1"
tonic = "0.9"

[build-dependencies]
tonic-build = "0.9"
