[package]
name = "bgpd"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
ipnet = "2.9.0"
nom = "7"
nom-derive = "0.10"
rusticata-macros = "4"
tokio = { version="1", features = ["full"] }
